### ISSUE TITLE
Necesidad de cambio de valores para cálculo de prima

### ISSUE THREAD

**Issue by cmonsalvec** [CarolinaBurgos/CalculadoraPrima#2]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by edsalloor** [comment]
Reproduciendo el error:
Se ha verificado que el número de puntos perdidos aceptados en la licencia para conductores con 65 años de edad o más y recibir la reducción en el valor de la prima, difiere de los 4 puntos aceptados actualmente por el directorio.
Se procederá a categorizar el incidente para luego ser asignado a un miembro del equipo.

**Comment by edsalloor** [comment]
Se ha realizado el análisis de impacto del incidente. Puede revisarlo en el siguiente enlace:
https://docs.google.com/document/d/1i6Yw4CNN5FHsV2mVUZfy-Yay4cKkplaapU5NjIkxyWE/edit?usp=sharing
Realizado el análisis esperamos su aprobación para realizar el cambio.

**Comment by cmonsalvec** [comment]
Muchas gracias, han realizado un buen análisis de impacto, estoy de acuerdo con los resultados, y pido por favor continuen con el cambio requerido.

**Comment by CarolinaBurgos** [comment]
Se ha realizado el paso 6 (Trabajar en la solución del incidente) de las 10 etapas de mantenimiento.
Enlace del commit: https://github.com/CarolinaBurgos/CalculadoraPrima/commit/415a73900e168828444a051f6b2cb5eff05979e3

**Comment by l-AngelMoya** [comment]
Se ha realizado el análisis de las pruebas de sistema con el cambio de reducción de puntos de la licencia para las personas de 65 años en adelante. 
https://espolec-my.sharepoint.com/:w:/g/personal/eduorsal_espol_edu_ec/EQGJLSdrEgtOoZnQ-Ok9mTUBZwAfiXrLEgIxfHIi_Gw6FQ?e=o2B9wl

**Comment by cmonsalvec** [comment]
Gracias por presentar el plan de pruebas, por favor me notifican si el cambio implementado logra pasar todas las pruebas planificadas

**Comment by l-AngelMoya** [comment]
Estimado @cmonsalvec, se procedió a correr las pruebas de sistema y el cambio implementado lograron pasar con éxito según lo planificado.

**Comment by edsalloor** [comment]
Prueba de aceptación:
Realizadas y verificadas las pruebas de sistema e integración, se han hecho los cambios pertinentes en la documentación.
https://espolec-my.sharepoint.com/:w:/g/personal/eduorsal_espol_edu_ec/EQGJLSdrEgtOoZnQ-Ok9mTUBZwAfiXrLEgIxfHIi_Gw6FQ?e=o2B9wl
Solicitamos su revisión, de no haber ningún inconveniente esperamos su validación conforme al cambio solicitado.

**Comment by cmonsalvec** [comment]
Estimados, he revisado las pruebas propuestas y su ejecución y estoy conforme con los resultados conseguidos. Favor proseguir

**Comment by edsalloor** [comment]
Cierre del Incidente:
Se ha verificado que se han realizado todas las tareas, por lo que se procede a cerrar el incidente. Se dará seguimiento a este módulo en producción, y cualquier novedad será comunicada en la página principal del proyecto.
Gracias por darnos a conocer su necesidad y mantener este proyecto activo.
